### PR TITLE
Updated `index.ts` with major bug fixes and new command

### PR DESCRIPTION
**Pull request by Diligord1**
- Fixed `--chat` argument doing literally absolutely nothing anywhere ever
- Now the user can't chat unless they can see the chat themselves (if they have `--chat` as one of their args)
- Added a `?quit` command, acts same as `?disconnect` or `?leave`

### CODE REVIEW

**Comment by hanatic** [comment]
• The first two points about `--chat` will be implemented ASAP. We had it in our original code but it seems it's got deleted somewhere along the way.
• I don't think the ?quit is very different or necessary.

**Comment by Diligord1** [comment]
> • The first two points about `--chat` will be implemented ASAP. We had it in our original code but it seems it's got deleted somewhere along the way. • I don't think the ?quit is very different or necessary.

Can I have contributor please 👍

**Comment by hanatic** [comment]
> Can I have contributor please 👍
Your commit hasn't yet been merged so we can't class you as a contributor.

**Comment by Diligord1** [comment]
> > Can I have contributor please 👍
> > Your commit hasn't yet been merged so we can't class you as a contributor.

makes sense

**Pull request merged**
