### PR TITLE
Auto-Updating System(Revised)

### PR DESCRIPTION
**Pull request by xploree**
To see the long description go look at my closed pull request, I don't feel like typing it all again

### CODE REVIEW

**Comment by hanatic** [comment]
This looks pretty good to me. However the code doesn't actually seem to run the updater in the .bat file. I'd update this if I was you.

**Comment by xploree** [comment]
> This looks pretty good to me. However the code doesn't actually seem to run the updater in the .bat file. I'd update this if I was you.

not sure how I missed that haha, i'll add it

**Comment by xploree** [comment]
alright I fixed it

**Comment by xploree** [comment]
😳

**Comment by xploree** [comment]
sorry for closing this so much just trying to perfect it

**Pull request closed without merging**
